trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Pay as you go'  # 🔁 Replace with your Azure RM service connection
  acrLoginServer: 'atulkamble.azurecr.io'
  acrUsername: 'atulkamblerepo'       # 🔁 Optional if using Azure service connection
  acrPassword: '$(acrPassword)'       # Set as secret variable in pipeline settings
  kubernetesCluster: 'aks-cluster'
  resourceGroup: 'aks-resource-group'
  containerRegistry: 'atulkamble'

stages:
  - stage: Build
    displayName: Build and Push Images
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build frontend image
            inputs:
              containerRegistry: '$(azureSubscription)'
              repository: 'frontend'
              command: buildAndPush
              Dockerfile: 'frontend/Dockerfile'
              tags: latest

          - task: Docker@2
            displayName: Build backend image
            inputs:
              containerRegistry: '$(azureSubscription)'
              repository: 'backend'
              command: buildAndPush
              Dockerfile: 'backend/Dockerfile'
              tags: latest

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        displayName: Deploy to AKS cluster
        environment: aks 
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: Set context for AKS
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '$(azureSubscription)'
                    azureResourceGroup: '$(resourceGroup)'
                    kubernetesCluster: '$(kubernetesCluster)'
                    command: 'login'

                - task: Kubernetes@1
                  displayName: Deploy manifests
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '$(azureSubscription)'
                    azureResourceGroup: '$(resourceGroup)'
                    kubernetesCluster: '$(kubernetesCluster)'
                    namespace: 'default'
                    command: apply
                    useConfigurationFile: true
                    configuration: 'manifests/full.yaml'
