trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'cc57cd42-dede-4674-b810-a0fbde41504a'
  acrName: 'atulkamble'
  kubernetesCluster: 'aks-cluster'
  resourceGroup: 'aks-resource-group'

stages:
  - stage: Build
    jobs:
      - job: BuildImages
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@02
            displayName: 'Build backend image'
            inputs:
              repository: 'backend'
              command: 'buildAndPush'
              Dockerfile: '**/backend/dockerfile'
              containerRegistry: '$(acrName)'
              tags: 'latest'

          - task: Docker@2
            displayName: 'Build frontend image'
            inputs:
              repository: 'frontend'
              command: 'buildAndPush'
              Dockerfile: '**/frontend/dockerfile'
              containerRegistry: '$(acrName)'
              tags: 'latest'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: 'aks-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: 'Deploy manifests to AKS'
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '$(azureSubscription)'
                    azureResourceGroup: '$(resourceGroup)'
                    kubernetesCluster: '$(kubernetesCluster)'
                    namespace: default
                    command: apply
                    useConfigurationFile: true
                    configuration: manifests/
