trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'azure-aks-connection'        # Azure Resource Manager service connection
  acrServiceConnection: 'atulkamble-acr'           # ✅ Docker Registry service connection name
  kubernetesCluster: 'aks-cluster'
  resourceGroup: 'aks-resource-group'

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: BuildAndPush
        displayName: Docker Build and Push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and Push Frontend Image
            inputs:
              command: buildAndPush
              containerRegistry: '$(acrServiceConnection)'   # ✅ Service connection name
              repository: 'frontend'
              dockerfile: 'frontend/Dockerfile'
              buildContext: 'frontend'
              tags: 'latest'

          - task: Docker@2
            displayName: Build and Push Backend Image
            inputs:
              command: buildAndPush
              containerRegistry: '$(acrServiceConnection)'   # ✅ Service connection name
              repository: 'backend'
              dockerfile: 'backend/Dockerfile'
              buildContext: 'backend'
              tags: 'latest'

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Build
    jobs:
      - job: DeployToAKS
        displayName: Apply Kubernetes Manifests
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: AKS Login and Set Context
            inputs:
              azureSubscription: '$(azureSubscription)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group $(resourceGroup) --name $(kubernetesCluster) --overwrite-existing
                kubectl apply -f manifests/full.yaml
