trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'acr'  # 🔁 Replace with actual service connection name
  acrLoginServer: 'atulkamble.azurecr.io'          # 🔁 Replace with actual ACR login server
  kubernetesCluster: 'aks-cluster'
  resourceGroup: 'aks-resource-group'

stages:
  - stage: Build
    jobs:
      - job: BuildImages
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Build backend image
          - task: Docker@1
            displayName: 'Build backend image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: '$(azureSubscription)'
              azureContainerRegistry: '$(acrLoginServer)'
              dockerFile: '**/backend/Dockerfile'
              imageName: 'backend:latest'
              command: 'Build an image'

          # Push backend image
          - task: Docker@1
            displayName: 'Push backend image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: '$(azureSubscription)'
              azureContainerRegistry: '$(acrLoginServer)'
              imageName: 'backend:latest'
              command: 'Push an image'

          # Build frontend image
          - task: Docker@1
            displayName: 'Build frontend image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: '$(azureSubscription)'
              azureContainerRegistry: '$(acrLoginServer)'
              dockerFile: '**/frontend/Dockerfile'
              imageName: 'frontend:latest'
              command: 'Build an image'

          # Push frontend image
          - task: Docker@1
            displayName: 'Push frontend image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: '$(azureSubscription)'
              azureContainerRegistry: '$(acrLoginServer)'
              imageName: 'frontend:latest'
              command: 'Push an image'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: 'aks-env'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: 'Deploy manifests to AKS'
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '$(azureSubscription)'
                    azureResourceGroup: '$(resourceGroup)'
                    kubernetesCluster: '$(kubernetesCluster)'
                    namespace: default
                    command: apply
                    useConfigurationFile: true
                    configuration: manifests/
